apiVersion: v1
kind: Namespace
metadata:
  name: backend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-k8s-dp
  namespace: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-lbl
      tier: backend
  template:
    metadata:
      labels:
        app: grpc-lbl
        tier: backend
    spec:
      containers:
        - name: grpc-server
          image: grpc-service:latest
          imagePullPolicy: Never
          livenessProbe:
            grpc:
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - mountPath: /app/assets
              name: shared-storage
      volumes:
        - name: shared-storage
          hostPath:
            path: /storage/images
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: grpc-k8s-srv
  namespace: backend
spec:
  clusterIP: None
  selector:
    app: grpc-lbl
  ports:
    - port: 8082
#  type: ClusterIP